### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by ChrisMaddock** [petabridge/NBench#116]
Was just having a look around for a better solution for our performance tests - NBench looks like a pretty interesting option!

Spotted a typo in the readme, just thought I'd point it out. I'd correct it, but I'm not sure what it's meant to say! In the `Benchmark Modes` section:

> During a Throughput benchmark the `Benchmark

Thanks - will be back if I hit further problems.

**Comment by Aaronontheweb** [comment]
@ChrisMaddock thanks! `Throughput` is a type of benchmark in NBench, hence why it's capitalized. The other type of mode is `Iteration`.
