### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by tigerclawn82** [petabridge/NBench#117]
Hi,
   I have tested generated markdown preview on multiple viewers but all of them failed to display properly except Github Editor. Is there any compatible viewer for Windows?

Thanks

**Comment by Aaronontheweb** [comment]
That's a  problem with the Markdown spec itself - no built-in support for tables. So we use Github flavored markdown.

I recommend using [Markdown Pad](http://markdownpad.com/) on Windows

**Comment by tigerclawn82** [comment]
Thanks :+1:

**Comment by aloisdg** [comment]
@tigerclawn82 Just to point that there is a nice exchange about [table](https://talk.commonmark.org/t/tables-in-pure-markdown/81) on CommonMark's forum. If you are curious :)
