### ISSUE TITLE
Support for TeamCity Test Service Messages?

### ISSUE THREAD

**Issue by IanMercer** [petabridge/NBench#128]
Any plans to include support for running under TeamCity and integrating into [their test reporting framework](https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-Supportedtestservicemessages)?

An approach similar to [NUnit's `ITestEventListener`](https://github.com/nunit/nunit/blob/329f6979529807009b166bbca028d0e4e6191973/src/NUnitEngine/Addins/teamcity-event-listener/TeamCityEventListener.cs) would be a useful addition making the content and formatting of the output more 'pluggable'.

**Comment by Aaronontheweb** [comment]
@IanMercer should be easy to write an `ITestOutput` adapter for that.... I'm a TeamCity user too so I would also like to see this.

**Comment by Aaronontheweb** [comment]
Have a burning need for this in Akka.NET - taking a look into it now
