### ISSUE TITLE
README.md inconsistent with code w.r.t. trace flag

### ISSUE THREAD

**Issue by bitwreckage** [petabridge/NBench#138]
README.md describes trace flag as:

> **tracing=true|false** - turns on trace capture inside the NBench runner ....

while in the code it seems the flag is really named "trace".
Should either correct README.md or support "tracing" as an alias for the "trace" flag in code.

**Comment by Aaronontheweb** [comment]
Thanks - I'll get this fixed in the docs.

**Comment by Aaronontheweb** [comment]
Ah, looks like it already is.
