### ISSUE TITLE
Thorughput time to execute accuracy wildly incorrect

### ISSUE THREAD

**Issue by jamesbascle** [petabridge/NBench#139]
I have a benchmark with this setting

```
    [PerfBenchmark(Description = "Test performance of Matching.", RunMode = RunMode.Throughput, RunTimeMilliseconds = 200, TestMode = TestMode.Test)]
```

It runs on average between 8-10 seconds.  
![image](https://cloud.githubusercontent.com/assets/4188293/19507842/602671be-95a3-11e6-9215-acf25d9b1c1c.png)

You can see the test here: https://github.com/jamesbascle/OneOf/blob/DiscU/OneOf.Tests/MatcherPerformanceTests.cs#L10

**Comment by alexpantyukhin** [comment]
Maybe setting `NumberOfIterations` parameter will work for you (for example 3). The default value is 10 for `NumberOfIterations` (https://github.com/petabridge/NBench/blob/126e1d9c832f57039a2f598ab47003216f22c728/src/NBench/PerformanceBenchmark.cs#L48) .

**Comment by jamesbascle** [comment]
Ahhhh.  I see.  I understood the documentation to mean that one used Throughput AND RunTimeMilliseconds OR  Iterations AND NumberOfIterations, not that those are used in conjunction.

**Comment by Aaronontheweb** [comment]
@jamesbascle sorry about that - we should rename this issue to clarify that in the documentation then I think. Isn't that the real issue here?
