### ISSUE TITLE
CLI should throw, or indicate when no benchmarks are found

### ISSUE THREAD

**Issue by heynickc** [petabridge/NBench#187]
Current behavior is if `ReflectionDiscovery.FindBenchmarks(assembly)` doesn't discover any benchmarks in the test assembly, it exits back to the command line.  This was happening in the end 2 end "NBench" target in build.fsx.  It didn't return exit code > 0, therefore still passed.  Should give users some indication that NBench.Runner didn't discover any benchmarks, especially if the user is confident that there are benchmarks in the target assembly.  Either failure/exception/error code or a message.

Maybe handling added to this block in TestRunner.cs:  https://github.com/petabridge/NBench/blob/dev/src/NBench/Sdk/TestRunner.cs#L206

**Comment by Aaronontheweb** [comment]
Completed - deprecated CLI - users can configure this through their own custom `Program.cs` implementation going forward.
