### ISSUE TITLE
LoadAssemblyCorrect for NBench.Tests.Performance.WithDependencies is flaky

### ISSUE THREAD

**Issue by heynickc** [petabridge/NBench#209]
This test was meant to verify that #192 was resolved, however it shows signs of flakiness in CI.

A clue as to why it's happening is whether or not it's running on the same build agent twice, or on a brand new build agent.  Hints towards an issue with disposing the AssemblyLoadContext in .NET Core correctly.

**Comment by Aaronontheweb** [comment]
Fixed by https://github.com/petabridge/NBench/pull/229
