### ISSUE TITLE
Nbench Runner Exception on VM

### ISSUE THREAD

**Issue by janmchan** [petabridge/NBench#219]
When I run a Nbench Runner on a VM, it crashes with this exception. I tried creating a simple application with just one method and it failed too. Here are the specs.

Unhandled Exception: System.ComponentModel.Win32Exception: The parameter is incorrect
   at System.Diagnostics.Process.set_ProcessorAffinity(IntPtr value)
   at NBench.Sdk.TestRunner.SetProcessPriority(Boolean concurrent)
   at NBench.Sdk.TestRunner.Execute()
   at NBench.Sdk.TestRunner.Execute()
   at NBench.Sdk.TestRunner.Run(TestPackage package)
   at NBench.Runner.Program.Main(String[] args)

Works in my local machine with the following details. In summary, it is a Windows 10 laptop
NBench=NBench, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=4
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2

Remote machine 
OS - Windows Server 2012 R2 Standard 6.3.9600
Processor Intel(R) Xeon(R) CPU E5-2676 v3 @2.40GHz, 2400 Mhz, 
ProcessorCount=1
.NET Framework 4.6.2 (394806)

 NBench version="1.0.4" targetFramework="net462"
NBench.Runner version="1.0.4" targetFramework="net462"

**Comment by Aaronontheweb** [comment]
@janmchan guess the issue here is that we're targeting CPU Core no. 2, which doesn't exist on a 1 core machine. We'll need to change the setting to target CPU Core no. 1.

**Comment by Aaronontheweb** [comment]
Should be resolved in NBench v1.2.0
