### ISSUE TITLE
There was a mismatch between the processor architecture of the project being built

### ISSUE THREAD

**Issue by williammoore0** [petabridge/NBench#221]
When building project in Visual Studio using build for Any CPU, and referencing NBench, recieve the following error:

There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "NBench.Runner, Version=1.0.4.0, Culture=neutral, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by Aaronontheweb** [comment]
Ah, fun stuff - AMD64 appears to be a new architecture; never seen that before. Might be something that's been added post-meltdown patch. I use a brand new Ryzen on my development machine. Let me shake some trees loose and see what shows up there.

**Comment by Aaronontheweb** [comment]
Resolved in 2.0 - NBench no longer contains an external runner. It gets built inside your own `Program.cs` and runs as a DLL. Will update the documentation accordingly once it ships in the next couple of days.
