### ISSUE TITLE
.Net Core: NU1605	Detected package downgrade: System.Reflection.TypeExtensions

### ISSUE THREAD

**Issue by bcbeatty** [petabridge/NBench#246]
When I try Install-Package NBench I'm getting the following error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: System.Reflection.TypeExtensions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 Remark.Performance.NBench.Tests -> NBench 1.2.0 -> NETStandard.Library 1.6.1 -> System.Linq.Expressions 4.3.0 -> System.Reflection.TypeExtensions (>= 4.3.0) 
 Performance.NBench.Tests -> NBench 1.2.0 -> System.Reflection.TypeExtensions (>= 4.1.0)	Performance.NBench.Tests	D:\\Performance.NBench.Tests.csproj	1	
`

this does not happen I target Net462

**Comment by Aaronontheweb** [comment]
We probably just need to upgrade those dependencies in the `NBench` library itself.

**Comment by Aaronontheweb** [comment]
Man, @bcbeatty you are right - this is really quite annoying!

**Comment by Aaronontheweb** [comment]
This can temporarily be solved by incorporating the following configuration into any of your affected projects:

```
<NoWarn>$(NoWarn);CS1591;NU1605</NoWarn>
```

That `NU1605` warning is standard inside most of our projects, which is why I didn't notice this before.

**Comment by Aaronontheweb** [comment]
Full example here:

https://github.com/petabridge/NBench/blob/95d3036e28c592eb508b7d5cc64a294441da4aa6/src/common.props#L2-L18
