### ISSUE TITLE
dotnet nbench command fails with the error "Version for package `dotnet-nbench` could not be resolved."

### ISSUE THREAD

**Issue by RusKnyaz** [petabridge/NBench#261]
Here is my project file:
`
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net462</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NBench" Version="1.2.2" />
      <PackageReference Include="NBench.Runner" Version="1.2.2" />
      <DotNetCliToolReference Include="dotnet-nbench" Version="1.2.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="perf" />
    </ItemGroup>
    
</Project>
`

Trying to execute 'dotnet nbench' command leads to the error "Version for package `dotnet-nbench` could not be resolved."

The issue is reproducible with any target framework. I checked it with the NBench '1.2.2' and '1.2.1'.

**Comment by Aaronontheweb** [comment]
Resolved via NBench 2.0.0 https://github.com/petabridge/NBench/releases/tag/2.0.0
