### ISSUE TITLE
Markdown formatting of tables

### ISSUE THREAD

**Issue by rogeralsing** [petabridge/NBench#64]
The current table markdown syntax seems to be compatible with Github tables.
It is not compatible with for example Marked.JS or Atom.IO's markdown preview.

The raw markdown is also hard to read due to column widths

```
          Metric |           Units |             Max |         Average |             Min |          StdDev |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
[Counter] InboundMessageDispatch |      operations |    1,099,208.00 |    1,099,208.00 |    1,099,208.00 |            0.00 |

          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
[Counter] InboundMessageDispatch |      operations |    2,785,603.36 |    2,503,310.64 |    1,983,111.20 |      271,163.13 |
```

It would be nice if the column width of the output text was calculated from the values contained in the columns.

Currently it is hard to read the output in both raw and rendered

**Comment by vamsitp** [comment]
Does the above work? I believe each line should start with a **|** for it to work?
https://help.github.com/articles/organizing-information-with-tables/

**Comment by Aaronontheweb** [comment]
Fixed this a while ago
