### ISSUE TITLE
CoreCLR support

### ISSUE THREAD

**Issue by jchannon** [petabridge/NBench#68]
Do you have any plans for this to work against CoreCLR apps especially those that run on OSX/Linux?

**Comment by Aaronontheweb** [comment]
@jchannon yes, absolutely - big part of our goal with the design of NBench was to support x-plat .NET development.

The only bummer might be that certain features we want to support for Windows users, such as `PerformanceCounter`, probably aren't going to make it into CoreCLR. So we'll have to reconcile that.

**Comment by Aaronontheweb** [comment]
Resolved this a long time ago as part of NBench 1.2*
