### ISSUE TITLE
Skip not working?

### ISSUE THREAD

**Issue by Benjol** [petabridge/NBench#80]
Maybe I haven't understood what it's supposed to do, but if you take your sample code and add Skip="whatever" and then do NBench Runner on it, it gets run.

**Comment by Aaronontheweb** [comment]
@Benjol should be working - I'll double check

**Comment by Aaronontheweb** [comment]
@Benjol fixed! Will be out in the next release, which I intend to do ASAP.

**Comment by Benjol** [comment]
Great, thanks!

**Comment by Aaronontheweb** [comment]
Argh, still having an issue with this in NBench v0.2.1, which is weird because my spec verifying that skipped benchmarks don't run passes >_<

**Comment by Aaronontheweb** [comment]
Nevermind, this was fixed already - had a NuGet issue in the project I was testing this in that was using the old v0.1.5 runner.
